# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

env:
  aws_access_key: ${{ secrets.aws_access_key }}
  aws_secret_key: ${{ secrets.aws_secret_key }}
  aws_session_token: ${{ secrets.aws_session_token }}
  aws_region: ${{ secrets.aws_region }}
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o app
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        # AWS Access Key
        aws_access_key: $aws_access_key
        # AWS Secret Key
        aws_secret_key: $aws_secret_key
        # AWS Session Token when using temporary security credentials such as when assuming a role in AWS through STS
        aws_session_token: $aws_session_token
        # AWS Region
        region: $aws_region
        # Beanstalk application name
        application_name: pucweb
        # Beanstalk environment name. If empty a version will be created but not deployed anywhere.
        environment_name: Pucweb-env
        # Version label for new Beanstalk version
        version_label: v${{ steps.date.outputs.date }}
